Repository cpuabuse/dungeon-together, pull requests merged in 2020-11, with the labels that each got.

#6 Add: Shard test template
  src/docs/comms.md
  test/data/shard.3-3-1.dt.json
Labels: enhancement

#8 Change: Class names for server universe
  src/app/client/client-cell.ts
  src/app/client/client-entity.ts
  src/app/client/client-grid.ts
  src/app/client/client-shard.ts
  src/app/client/client-universe.ts
  src/app/client/connection.ts
  src/app/client/scene.ts
  src/app/client/square.ts
  src/app/common/defaults.ts
  src/app/comms/comms-entity.ts
  src/app/comms/comms-universe.ts
  src/app/server/server-cell.ts
  src/app/server/server-entity.ts
  src/app/server/server-grid.ts
  src/app/server/server-proto.ts
  src/app/server/server-shard.ts
  src/app/server/server-universe.ts
Labels: enhancement

#7 Add: Test outline and docs
  .vscode/settings.json
  src/docs/pool.md
  src/docs/universe.md
  test/integration/test.ts
  test/system/test.ts
  test/test.ts
  test/unit/test.ts
Labels: documentation, enhancement

#10 Change: Client-side class names
  src/app/client/client-entity.ts
  src/app/client/connection.ts
  src/app/comms/comms-grid.ts
Labels: enhancement

#9 Change: Class names for server files
  src/app/server/server-cell.ts
  src/app/server/server-entity.ts
  src/app/server/server-grid.ts
  src/app/server/server-proto.ts
  src/app/server/server-shard.ts
  src/app/server/server-universe.ts
Labels: enhancement

#11 Change: Client main
  src/app/client.ts
Labels: enhancement

#12 Change: Server side files class names
  src/app/client/client-universe.ts
  src/app/server/kind.ts
  src/app/server/server-cell.ts
  src/app/server/server-entity.ts
  src/app/server/server-grid.ts
  src/app/server/server-shard.ts
  src/app/server/server-universe.ts
Labels: enhancement

#14 Change: Docs
  src/docs/software_requirements.md
Labels: documentation
